<html xmlns:wso="http://www.dataaccess.com/schemas/WebServiceMetaData">
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <style type="text/css">
                    body
                    {
                        margin-left: 2em;
                    }                
                    h1
                    {
                        margin-left: -0.8em;
                    }                
                    h2
                    {
                        margin-left: -0.8em;
                        border-top: 1px solid;
                    }                
                    h3
                    {
                        margin-left: -0.8em;
                    }                
                    .title
                    {
                        margin-left: -0.8em;
                        color: #000080;
                        font-size: 1.7em;
                        background-color: #99ccff;
                        padding-top: 0.3em;
                        padding-bottom: 0.3em;
                    } 
                    .intro
                    {
                        margin-left: -0.8em;
                    }
                    .frmheader
                    {
                        background: #dcdcdc;
                        padding-top: 0.1em;
                        padding-bottom: 0.2em;
                    }
                    .code
                    {
                        font-family: 'Courier New';
                        background-color: lightyellow;
                        padding: 0.3em;
                    }
                    font.value
                    {
                        color: darkblue;
                        font: bold;
                    }
                    font.key
                    {
                        color: darkgreen;
                        font: bold;
                    }
                </style>
    <title>DataFlex Web Service for Country information</title>
  </head>
  <body>
    <center>
      <p class="title">DataFlex Web Service for Country information</p>
    </center>
    <p>
      <span>This DataFlex Web Service opens up country information. 2 letter ISO codes are used for Country code. There are functions to retrieve the used Currency, Language, Capital City, Continent and Telephone code.</span>
    </p>
                The following operations are available. For a formal definition, please review the
                <a href="/websamples.countryinfo/CountryInfoService.wso?WSDL">Service Description</a>.
        <ul>
      <li>
        <b><a href="/websamples.countryinfo/CountryInfoService.wso?op=ListOfContinentsByName">ListOfContinentsByName</a></b>
        <br>
        <span>Returns a list of continents ordered by name.</span>
      </li>
      <p></p>
      <li>
        <b><a href="/websamples.countryinfo/CountryInfoService.wso?op=ListOfContinentsByCode">ListOfContinentsByCode</a></b>
        <br>
        <span>Returns a list of continents ordered by code.</span>
      </li>
      <p></p>
      <li>
        <b><a href="/websamples.countryinfo/CountryInfoService.wso?op=ListOfCurrenciesByName">ListOfCurrenciesByName</a></b>
        <br>
        <span>Returns a list of currencies ordered by name.</span>
      </li>
      <p></p>
      <li>
        <b><a href="/websamples.countryinfo/CountryInfoService.wso?op=ListOfCurrenciesByCode">ListOfCurrenciesByCode</a></b>
        <br>
        <span>Returns a list of currencies ordered by code.</span>
      </li>
      <p></p>
      <li>
        <b><a href="/websamples.countryinfo/CountryInfoService.wso?op=CurrencyName">CurrencyName</a></b>
        <br>
        <span>Returns the name of the currency (if found)</span>
      </li>
      <p></p>
      <li>
        <b><a href="/websamples.countryinfo/CountryInfoService.wso?op=ListOfCountryNamesByCode">ListOfCountryNamesByCode</a></b>
        <br>
        <span>Returns a list of all stored counties ordered by ISO code</span>
      </li>
      <p></p>
      <li>
        <b><a href="/websamples.countryinfo/CountryInfoService.wso?op=ListOfCountryNamesByName">ListOfCountryNamesByName</a></b>
        <br>
        <span>Returns a list of all stored counties ordered by country name</span>
      </li>
      <p></p>
      <li>
        <b><a href="/websamples.countryinfo/CountryInfoService.wso?op=ListOfCountryNamesGroupedByContinent">ListOfCountryNamesGroupedByContinent</a></b>
        <br>
        <span>Returns a list of all stored counties grouped per continent</span>
      </li>
      <p></p>
      <li>
        <b><a href="/websamples.countryinfo/CountryInfoService.wso?op=CountryName">CountryName</a></b>
        <br>
        <span>Searches the database for a country by the passed ISO country code</span>
      </li>
      <p></p>
      <li>
        <b><a href="/websamples.countryinfo/CountryInfoService.wso?op=CountryISOCode">CountryISOCode</a></b>
        <br>
        <span>This function tries to found a country based on the passed country name.</span>
      </li>
      <p></p>
      <li>
        <b><a href="/websamples.countryinfo/CountryInfoService.wso?op=CapitalCity">CapitalCity</a></b>
        <br>
        <span>Returns the  name of the captial city for the passed country code</span>
      </li>
      <p></p>
      <li>
        <b><a href="/websamples.countryinfo/CountryInfoService.wso?op=CountryCurrency">CountryCurrency</a></b>
        <br>
        <span>Returns the currency ISO code and name for the passed country ISO code</span>
      </li>
      <p></p>
      <li>
        <b><a href="/websamples.countryinfo/CountryInfoService.wso?op=CountryFlag">CountryFlag</a></b>
        <br>
        <span>Returns a link to a picture of the country flag</span>
      </li>
      <p></p>
      <li>
        <b><a href="/websamples.countryinfo/CountryInfoService.wso?op=CountryIntPhoneCode">CountryIntPhoneCode</a></b>
        <br>
        <span>Returns the internation phone code for the passed ISO country code</span>
      </li>
      <p></p>
      <li>
        <b><a href="/websamples.countryinfo/CountryInfoService.wso?op=FullCountryInfo">FullCountryInfo</a></b>
        <br>
        <span>Returns a struct with all the stored country information. Pass the ISO country code</span>
      </li>
      <p></p>
      <li>
        <b><a href="/websamples.countryinfo/CountryInfoService.wso?op=FullCountryInfoAllCountries">FullCountryInfoAllCountries</a></b>
        <br>
        <span>Returns an array with all countries and all the language information stored</span>
      </li>
      <p></p>
      <li>
        <b><a href="/websamples.countryinfo/CountryInfoService.wso?op=CountriesUsingCurrency">CountriesUsingCurrency</a></b>
        <br>
        <span>Returns a list of all countries that use the same currency code. Pass a ISO currency code</span>
      </li>
      <p></p>
      <li>
        <b><a href="/websamples.countryinfo/CountryInfoService.wso?op=ListOfLanguagesByName">ListOfLanguagesByName</a></b>
        <br>
        <span>Returns an array of languages ordered by name</span>
      </li>
      <p></p>
      <li>
        <b><a href="/websamples.countryinfo/CountryInfoService.wso?op=ListOfLanguagesByCode">ListOfLanguagesByCode</a></b>
        <br>
        <span>Returns an array of languages ordered by code</span>
      </li>
      <p></p>
      <li>
        <b><a href="/websamples.countryinfo/CountryInfoService.wso?op=LanguageName">LanguageName</a></b>
        <br>
        <span>Find a language name based on the passed ISO language code</span>
      </li>
      <p></p>
      <li>
        <b><a href="/websamples.countryinfo/CountryInfoService.wso?op=LanguageISOCode">LanguageISOCode</a></b>
        <br>
        <span>Find a language ISO code based on the passed language name</span>
      </li>
      <p></p>
    </ul>
  </body>
</html>
